answer/urls.py

from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import url

from django.conf import settings
from django.conf.urls.static import static
from . import views
from .views import *

app_name = 'answer'
urlpatterns = [
    path('test/', views.test_start, name='test_start'),
    path('result/', views.test_start, name='test_result'),


]
  

settings/urls.py

from django.contrib import admin
from django.urls import path, include
from testapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='home'),

    # path('api-auth/', include('rest_framework.urls')),
    path('testapp/', include('testapp.urls', namespace="testapp"), ),
    path('answer/', include('answer.urls', namespace="answer"), ),


]

testapp/urls.py

from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import url

from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'testapp'
urlpatterns = [
    path('', views.test_list, name='product_list'),
    path('<slug:category_slug>/', views.test_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.test_detail, name='test_detail'),
    # path('test/', views.test_start, name='test_startt'),





    # url(r'^(?P<category_slug>[-\w]+)/$',
    #     views.product_list,
    #     name='product_list_by_category'),


    # path('', IndexView.as_view(), name='testapp'),
    # re_path(r'^(?P<pk>\d+)/$', PollDetailView.as_view(), name='detail'),
    # re_path(r'^(?P<poll_id>\d+)/vote/$', vote, name='vote'),
    # re_path(r'^(?P<pk>\d+)/results/$', ResultsView.as_view(), name='results'),
]

testapp/models.py
from django.db import models
from django.urls import reverse
import datetime
from settings import settings

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200,db_index=True, unique=True)
    
    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
    
    def __str__(self):
        return self.name
    
    
    def get_absolute_url(self):
        return reverse('testapp:product_list_by_category',
                        args=[self.slug])

class Profile(models.Model):
    category = models.ForeignKey(Category, on_delete = models.CASCADE, related_name='products', verbose_name='Категория')
    name = models.CharField(max_length=200, verbose_name='Название теста')
    work_time = models.IntegerField(verbose_name='Время выполнения (мин)')
    questions_count = models.IntegerField(verbose_name='Количество вопросов')
    statisfactorily = models.IntegerField(verbose_name='Удовлетворительно')
    good = models.IntegerField(verbose_name='Хорошо')
    perfect = models.IntegerField(verbose_name='Отлично')
    slug = models.SlugField(max_length=200, db_index=True, null=True)

    class Meta:
        verbose_name = 'Тесты'
        verbose_name_plural = 'Тесты'

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('testapp:test_detail', args=[self.id, self.slug])




class Question(models.Model):
    """Вопрос"""
    profile_name = models.ForeignKey(Profile, null=True, on_delete=models.CASCADE, verbose_name='Название теста')
    question = models.CharField(max_length=200, verbose_name = "Вопрос")
    option1 = models.CharField(max_length=200, verbose_name = "Вариант №1")
    option2 = models.CharField(max_length=200, verbose_name = "Вариант №2")
    option3 = models.CharField(max_length=200, verbose_name = "Вариант №3")
    option4 = models.CharField(max_length=200, verbose_name = "Вариант №4")
    answer = models.CharField(max_length=200,null=True, verbose_name = "Верный ответ")
    weight = models.FloatField(default=1, verbose_name='Вес')
    date_published = models.DateTimeField(verbose_name = "Дата публикации", default = datetime.datetime.now())
    is_active = models.BooleanField(verbose_name = "Опубликован")
    slug = models.SlugField(max_length=200, db_index=True, null=True)


    class Meta:
        verbose_name = 'Вопрос'
        verbose_name_plural = 'Вопросы'
   
    
    def __str__(self):
        return self.question

    def get_absolute_url(self):
        return reverse('testapp:test_start', args=[ self.id])

class Result(models.Model):
    profile_id = models.ForeignKey(Profile, on_delete=models.CASCADE, verbose_name='Тест')
    username = models.CharField(max_length=300, verbose_name="ФИО")
    date_time = models.DateTimeField(auto_now_add=True, blank=True, verbose_name="Время завершения")
    rating =models.FloatField(verbose_name="Проценты")

    class Meta:
        verbose_name = 'Результат'
        verbose_name_plural = 'Результаты'

testapp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views.generic import ListView, DetailView
from .models import Profile, Category, Question
from django.contrib.auth import get_user_model

User = get_user_model()

def index(request):
    profile = Profile.objects.all()
    category = Category.objects.all()


#     page_obj = paginator(request, post_list)
    context = {
        'category': category,
        'profile': profile,
        'index': True,
    }
    return render(request, 'index.html', context)

     
# def cart_detail_test(request, test_id):
#     profile = get_object_or_404(Profile, id=test_id)

#     answer = Answer.objects.all()
#     question = Question.objects.all()
#     print(question)

#     context = {
#         'profile': profile,
#         'answer': answer,
#         'question': question,

#     }
#     template = 'testapp/cart_detail_test.html'
#     return render(request, template, context)

def test_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    profile = Profile.objects.filter()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        profile = profile.filter(category=category)
        
        
    context = {
        'category': category,
        'categories': categories,
        'profile': profile}

    
    template = 'testapp/test_list.html'
    return render(request, template, context)


def test_detail(request, id, slug):
    profile = get_object_or_404(Profile, id=id, slug=slug)       
    context = {
        'profile': profile,
    }
    template = 'testapp/test_detail.html'
    return render(request, template, context)



testapp/templates/testapp/result.html
{% extends "base.html" %}

{% block content %}

<div class="container ">
        
    <div class="card-columns" style="padding: 10px; margin: 20px;">
        <div class="card" align="centre " style="width: 32rem; border:5px black solid">
            <img class="card-img-top" src="http://kmit.in/emagazine/wp-content/uploads/2018/02/karnataka-results.jpg" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">Score: {{score}}</h5>

                <p class="card-text">Percentage: {{percent}}%</p>
                <p class="card-text">Time Taken: {{time}} seconds</p>
                <p class="card-text">Correct answers: {{correct}}</p>
                <p class="card-text">Incorrect answers: {{wrong}}</p>
                <p class="card-text">Total questions: {{total}}</p>
                <h5>All the best for next quiz!</h5>
            </div>
        </div>
    </div>

</div>

{% endblock %}

testapp/templates/testapp/test_detail.html
{% extends "base.html" %}
{% block content %}
  <main role="main">
        <div class="container mb-5">
            <div class="row">
                {% if profile %}
                    <div class="col-md-5">
               

                        <h3> Название теста - {{ profile.name }}</h3>
                        <p>Время выполнения (мин) &nbsp;-&nbsp;{{ profile.work_time }}</p>
                        <p>Количество вопросов (шт.) &nbsp;-&nbsp;{{ profile.questions_count }}</p>
                    </div>
                {% endif %}
            </div>

                <a href="{% url "answer:test_start" %}"><button type="submit" class="btn btn-primary">Начать тест</button></a>
    </div>
    </main> 
{% endblock %} 
                         



testapp/templates/testapp/test_list.html
 {% extends "base.html" %} 
{% load static %}

{% block title %}
    {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}

{% block content %}
    <div id="sidebar">
        <h3>Категории</h3>
        <ul>
            <li {% if not category %}class="selected"{% endif %}>
                <a href="{% url "testapp:product_list" %}">Все тесты</a>
            </li>
            {% for c in categories %}
                <li {% if category.slug == c.slug %}class="selected"{% endif %}>
                    <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div id="main" class="product-list">
        <h1>{% if category %}{{ category.name }}{% else %}Тесты{% endif %}</h1>
        {% for item_profile in profile %}
            <div class="item">
                {% comment %} <a href="{{ product.get_absolute_url }}">
                    <img src="{% if product.image %}{{ product.image.url }}{%else%}{% static "img/no_image.png" %}{% endif %}">
                </a> {% endcomment %}
                <a href="{{ item_profile.get_absolute_url }}">{{ item_profile.name }}</a>

            </div>
        {% endfor %}
    </div>
{% endblock %}